### ISSUE TITLE
TAP producers for other languages

### ISSUE THREAD

**Issue by ghost** [sindresorhus/awesome-tap#3]
I have written a TAP producer and harness for the fish-shell, [Fishtape](https://github.com/fisherman/fishtape). I would like to add it the list, but I don't know if you want to keep this list to mostly JavaScript or only more mainstream languages.

**Comment by sindresorhus** [comment]
See note at the top of the readme. It's only JS focused since that's the ecosystem I know. Happy to add stuff from other languages.

**Comment by ghost** [comment]
Great! Thanks.
